DEP_INCLUDES = -I ../../global
DEP_INCLUDES += -I ../../core/includes
DEP_INCLUDES += -I ../../io/includes
DEP_INCLUDES += -I ../../arch/cpu/includes
DEP_INCLUDES += -I ../../lib/libapi/includes
DEP_INCLUDES += -I ../../lib/libstruct/includes
DEP_INCLUDES += -I includes
DEP_INCLUDES += -I ../../tests/includes
DEP_LIBS=